<?php
/**
 * MediaRepository.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MediaRepository
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Wed May 30 16:44:53 CEST 2012.
 */

use Doctrine\ORM\Mapping as ORM;

/**
* Entity extension domain class storing medium attributes.
 *
 * This is the concrete attribute class for medium entities.
* @ORM\Entity(repositoryClass="MediaRepository_Entity_Repository_Base_MediumAttribute")
   * @ORM\Table(name="medrep_medium_attribute",
   *     uniqueConstraints={
   *         @ORM\UniqueConstraint(name="cat_unq", columns={"name", "entityId"})
   *     }
   * )
 */
class MediaRepository_Entity_MediumAttribute extends MediaRepository_Entity_Base_MediumAttribute
{
    // feel free to add your own methods here
}
