<?php
/**
 * MediaRepository.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MediaRepository
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Fri Jun 22 18:45:35 CEST 2012.
 */

use Doctrine\ORM\Mapping as ORM;

/**
* Entity extension domain class storing repository categories.
 *
 * This is the concrete category class for repository entities.
* @ORM\Entity(repositoryClass="MediaRepository_Entity_Repository_Base_RepositoryCategory")
   * @ORM\Table(name="medrep_repository_category",
   *     uniqueConstraints={
   *         @ORM\UniqueConstraint(name="cat_unq", columns={"registryId", "categoryId", "entityId"})
   *     }
   * )
 */
class MediaRepository_Entity_RepositoryCategory extends MediaRepository_Entity_Base_RepositoryCategory
{
    // feel free to add your own methods here
}
