<?php
/**
 * MediaRepository.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MediaRepository
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Fri Jun 22 18:45:37 CEST 2012.
 */

/**
 * Search api base class.
 */
class MediaRepository_Api_Base_Search extends Zikula_AbstractApi
{
    /**
     * Get search plugin information.
     *
     * @return array The search plugin information
     */
    public function info()
    {
        return array('title'     => $this->name,
                     'functions' => array($this->name => 'search'));
    }
    
    /**
     * Display the search form.
     *
     * @param array $args List of arguments.
     *
     * @return string template output
     */
    public function options($args)
    {
        if (!SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_READ)) {
            return '';
        }
    
        $view = Zikula_View::getInstance($this->name);
    
        $view->assign('active_repository', (!isset($args['active_repository']) || isset($args['active']['active_repository'])));
        $view->assign('active_mediaHandler', (!isset($args['active_mediaHandler']) || isset($args['active']['active_mediaHandler'])));
        $view->assign('active_medium', (!isset($args['active_medium']) || isset($args['active']['active_medium'])));
        $view->assign('active_thumbSize', (!isset($args['active_thumbSize']) || isset($args['active']['active_thumbSize'])));
    
        return $view->fetch('search/options.tpl');
    }
    
    /**
     * Executes the actual search process.
     *
     * @param array $args List of arguments.
     *
     * @return boolean
     */
    public function search($args)
    {
        if (!SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_READ)) {
            return '';
        }
    
        // ensure that database information of Search module is loaded
        ModUtil::dbInfoLoad('Search');
    
        // save session id as it is used when inserting search results below
        $sessionId  = session_id();
    
        // retrieve list of activated object types
        $searchTypes = isset($args['objectTypes']) ? (array)$args['objectTypes'] : (array)FormUtil::getPassedValue('search_mediarepository_types', array(), 'GETPOST');
    
        $controllerHelper = new MediaRepository_Util_Controller($this->serviceManager);
        $utilArgs = array('api' => 'search', 'action' => 'search');
        $allowedTypes = $controllerHelper->getObjectTypes('api', $utilArgs);
        $entityManager = ServiceUtil::getService('doctrine.entitymanager');
        $currentPage = 1;
        $resultsPerPage = 50;
    
        foreach ($searchTypes as $objectType) {
            if (!in_array($objectType, $allowedTypes)) {
                continue;
            }
    
            $whereArray = array();
            $languageField = null;
            switch ($objectType) {
                case 'repository':
                    $whereArray[] = 'name';
                    $whereArray[] = 'workDirectory';
                    $whereArray[] = 'storageDirectory';
                    $whereArray[] = 'cacheDirectory';
                    $whereArray[] = 'uploadNamingPrefix';
                    $whereArray[] = 'mailRecipient';
                    break;
                case 'mediaHandler':
                    $whereArray[] = 'mimeType';
                    $whereArray[] = 'fileType';
                    $whereArray[] = 'foundMimeType';
                    $whereArray[] = 'foundFileType';
                    $whereArray[] = 'handlerName';
                    $whereArray[] = 'title';
                    $whereArray[] = 'image';
                    break;
                case 'medium':
                    $whereArray[] = 'title';
                    $whereArray[] = 'keywords';
                    $whereArray[] = 'description';
                    $whereArray[] = 'description2';
                    $whereArray[] = 'dateTaken';
                    $whereArray[] = 'placeTaken';
                    $whereArray[] = 'notes';
                    $whereArray[] = 'license';
                    $whereArray[] = 'areamap';
                    $whereArray[] = 'url';
                    $whereArray[] = 'mediaHandler';
                    $whereArray[] = 'fileUpload';
                    break;
                case 'thumbSize':
                    $whereArray[] = 'name';
                    break;
            }
            $where = Search_Api_User::construct_where($args, $whereArray, $languageField);
    
            $repository = $entityManager->getRepository($this->name . '_Entity_' . ucfirst($objectType));
            // get objects from database
            list($entities, $objectCount) = $repository->selectWherePaginated($where, '', $currentPage, $resultsPerPage, false);
    
            if ($objectCount == 0) {
                continue;
            }
    
            $idFields = ModUtil::apiFunc($this->name, 'selection', 'getIdFields', array('ot' => $objectType));
            $titleField = $repository->getTitleFieldName();
            $descriptionField = $repository->getDescriptionFieldName();
            foreach ($entities as $entity) {
                $urlArgs = array('ot' => $objectType);
                // create identifier for permission check
                $instanceId = '';
                foreach ($idFields as $idField) {
                    $urlArgs[$idField] = $entity[$idField];
                    if (!empty($instanceId)) {
                        $instanceId .= '_';
                    }
                    $instanceId .= $entity[$idField];
                }
                $urlArgs['id'] = $instanceId;
                if (isset($entity['slug'])) {
                    $urlArgs['slug'] = $entity['slug'];
                }
    
                if (!SecurityUtil::checkPermission($this->name . ':' . ucfirst($objectType) . ':', $instanceId . '::', ACCESS_OVERVIEW)) {
                    continue;
                }
    
                $title = ($titleField != '') ? $entity[$titleField] : $this->__('Item');
                $description = ($descriptionField != '') ? $entity[$descriptionField] : '';
                $created = (isset($entity['createdDate'])) ? $entity['createdDate'] : '';
    
                $searchItem = array(
                    'title'   => $title,
                    'text'    => $description,
                    'extra'   => serialize($urlArgs),
                    'created' => $created,
                    'module'  => $this->name,
                    'session' => $sessionId
                );
    
                if (!DBUtil::insertObject($searchItem, 'search_result')) {
                    return LogUtil::registerError($this->__('Error! Could not save the search results.'));
                }
            }
        }
    
        return true;
    }
    
    /**
     * Assign URL to items.
     *
     * @param array $args List of arguments.
     *
     * @return boolean
     */
    public function search_check($args)
    {
        $datarow = &$args['datarow'];
        $urlArgs = unserialize($datarow['extra']);
        $datarow['url'] = ModUril::url($this->name, 'user', 'display', $urlArgs);
        return true;
    }
}
