<?php
/**
 * MediaRepository.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MediaRepository
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Fri Jun 22 18:45:35 CEST 2012.
 */

use Doctrine\ORM\Mapping as ORM;

/**
* Entity extension domain class storing repository categories.
 *
 * This is the base category class for repository entities.
 */
class MediaRepository_Entity_Base_RepositoryCategory extends Zikula_Doctrine2_Entity_EntityCategory
{
    /**
* @ORM\ManyToOne(targetEntity="MediaRepository_Entity_Repository", inversedBy="categories")
     * @ORM\JoinColumn(name="entityId", referencedColumnName="id")
     * @var MediaRepository_Entity_Repository
     */
    protected $entity;

    /**
     * Get reference to owning entity.
     *
     * @return MediaRepository_Entity_Repository
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Set reference to owning entity.
     *
     * @param MediaRepository_Entity_Repository $entity
     */
    public function setEntity(/*MediaRepository_Entity_Repository */$entity)
    {
        $this->entity = $entity;
    }
}
