<?php
/**
 * MediaRepository.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MediaRepository
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Wed May 30 16:44:53 CEST 2012.
 */

/**
 * The mediarepositoryImageThumb modifier displays a thumbnail image.
 *
 * @param  string $filePath  The input file path (including the file name).
 * @param  int    $width     Desired width.
 * @param  int    $height    Desired height.
 * @param  array  $thumbArgs Additional arguments.
 *
 * @return string The thumbnail file path.
 */
function smarty_modifier_mediarepositoryImageThumb($filePath = '', $width = 100, $height = 80, $thumbArgs = array())
{
    /**
     * By overriding this plugin or the util method called below you may add further thumbnail arguments
     * based on custom conditions.
     */
    return MediaRepository_Util_Image::getThumb($filePath, $width, $height, $thumbArgs);
}
