<?php
/**
 * MediaRepository.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MediaRepository
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Fri Jun 22 18:45:36 CEST 2012.
 */

/**
 * Event handler implementation class for events of the Users module.
 */
class MediaRepository_Listener_Users
{
     	    /**
     	     * Listener for the `module.users.config.updated` event.
     	     *
     	     * Occurs after the Users module configuration has been
     	     * updated via the administration interface.
     	     *
     	     * @param Zikula_Event $event The event instance.
     	     */
     	    public static function configUpdated(Zikula_Event $event)
     	    {
     	    }
}
