<?php
/**
 * MediaRepository.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MediaRepository
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Fri Jun 22 18:45:36 CEST 2012.
 */

/**
 * This handler class handles the page events of the Form called by the MediaRepository_user_edit() function.
 * It collects common functionality required by different object types.
 */
class MediaRepository_Form_Handler_User_Edit extends MediaRepository_Form_Handler_User_Base_Edit
{
    // feel free to extend the base handler class here
}
