<?php

/**
 * MediaRepository.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MediaRepository
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Fri Jun 22 18:45:36 CEST 2012.
 */

/**
 * Utility implementation class for controller helper methods.
 */
class MediaRepository_Util_Controller extends MediaRepository_Util_Base_Controller {
    // feel free to add your own convenience methods here

    

}
