<?php
/**
 * MediaRepository.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MediaRepository
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Wed May 30 16:44:53 CEST 2012.
 */

/**
 * Generic single item display content plugin base class.
 */
class MediaRepository_ContentType_Base_Item extends Content_AbstractContentType
{
    protected $objectType;
    protected $id;
    protected $displayMode;
    
    /**
     * Returns the module providing this content type.
     *
     * @return string The module name.
     */
    public function getModule()
    {
        return 'MediaRepository';
    }
    
    /**
     * Returns the name of this content type.
     *
     * @return string The content type name.
     */
    public function getName()
    {
        return 'Item';
    }
    
    /**
     * Returns the title of this content type.
     *
     * @return string The content type title.
     */
    public function getTitle()
    {
        $dom = ZLanguage::getModuleDomain('MediaRepository');
        return __('MediaRepository detail view', $dom);
    }
    
    /**
     * Returns the description of this content type.
     *
     * @return string The content type description.
     */
    public function getDescription()
    {
        $dom = ZLanguage::getModuleDomain('MediaRepository');
        return __('Display or link a single MediaRepository object.', $dom);
    }
    
    /**
     * Loads the data.
     *
     * @param array $data Data array with parameters.
     */
    public function loadData(&$data)
    {
        $utilArgs = array('name' => 'detail');
        if (!isset($data['objectType']) || !in_array($data['objectType'], MediaRepository_Util_Controller::getObjectTypes('contentType', $utilArgs))) {
            $data['objectType'] = MediaRepository_Util_Controller::getDefaultObjectType('contentType', $utilArgs);
        }
    
        $this->objectType = $data['objectType'];
    
        if (!isset($data['id'])) {
            $data['id'] = null;
        }
        if (!isset($data['displayMode'])) {
            $data['displayMode'] = 'embed';
        }
    
        $this->id = $data['id'];
        $this->displayMode = $data['displayMode'];
    }
    
    /**
     * Displays the data.
     *
     * @return string The returned output.
     */
    public function display()
    {
        if ($this->id != null && !empty($this->displayMode)) {
            return ModUtil::func('MediaRepository', 'external', 'display', $this->getDisplayArguments());
        }
        return '';
    }
    
    /**
     * Displays the data for editing.
     */
    public function displayEditing()
    {
        if ($this->id != null && !empty($this->displayMode)) {
            return ModUtil::func('MediaRepository', 'external', 'display', $this->getDisplayArguments());
        }
        $dom = ZLanguage::getModuleDomain('MediaRepository');
        return __('No item selected.', $dom);
    }
    
    /**
     * Returns common arguments for display data selection with the external api.
     *
     * @return array Display arguments.
     */
    protected function getDisplayArguments()
    {
        return array('objectType' => $this->objectType,
                     'source' => 'contentType',
                     'displayMode' => $this->displayMode,
                     'id' => $this->id
        );
    }
    
    /**
     * Returns the default data.
     *
     * @return array Default data and parameters.
     */
    public function getDefaultData()
    {
        return array('objectType' => 'medium',
                     'id' => null,
                     'displayMode' => 'embed');
    }
    
    /**
     * Executes additional actions for the editing mode.
     */
    public function startEditing()
    {
        // ensure our custom plugins are loaded
        array_push($this->view->plugins_dir, 'modules/MediaRepository/templates/plugins');
    
        // required as parameter for the item selector plugin
        $this->view->assign('objectType', $this->objectType);
    }
}
