<?php
/**
 * MediaRepository.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MediaRepository
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Fri Jun 22 18:45:37 CEST 2012.
 */

/**
 * Generic single item display content plugin implementation class.
 */
class MediaRepository_ContentType_Item extends MediaRepository_ContentType_Base_Item
{
    // feel free to extend the content type here
}

function MediaRepository_Api_ContentTypes_item($args)
{
    return new MediaRepository_Api_ContentTypes_itemPlugin();
}
