<?php
/**
 * MediaRepository.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MediaRepository
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Fri Jun 22 18:45:35 CEST 2012.
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for media handler entities.
 */
class MediaRepository_Entity_Validator_MediaHandler extends MediaRepository_Entity_Validator_Base_MediaHandler
{
    // here you can add custom validation methods or override existing checks
}
