<?php
/**
 * MediaRepository.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MediaRepository
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Fri Jun 22 18:45:37 CEST 2012.
 */

/**
 * This class provides object meta data for the Tag module.
 */
class MediaRepository_TaggedObjectMeta_MediaRepository extends MediaRepository_TaggedObjectMeta_Base_MediaRepository
{
    // feel free to extend the tag support here
}
